{% set name = "cpr" %}
{% set version = "1.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/libcpr/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: c55d805300c224f099cad74ad9c68799f23d005d09ba2df76ead975a3e50e09d
  patches:
    # conda-forge's curl uses autotools, so we cannot use cmake COMPONENTS
    - patches/find_package_curl.patch

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
  host:
    - libcurl
    - openssl

test:
  commands:
    - test -f ${PREFIX}/lib/libcpr.so
    - test -f ${PREFIX}/include/cpr/cpr.h

about:
  home: https://github.com/libcpr/cpr
  dev_url: https://github.com/libcpr/cpr
  license: MIT
  license_file: LICENSE
  summary: "C++ Requests: Curl for People"
  description: "C++ Requests is a simple wrapper around libcurl inspired by the excellent Python Requests project."

extra:
  recipe-maintainers:
    - anderslindho
